### ISSUE TITLE
Update 'Installation part' with all the work made on ansible-role-octopussy

### ISSUE THREAD

**Issue by sebthebert** [Octopussy-Project/Octopussy_Documentation#7]
* [ ] update with link to Ansible role
  * [ ] add all the missing stuff discovered while working on that role

**Comment by jlozadad** [comment]
I can't find the ansible role in ansible galaxy or anywhere.

**Comment by sebthebert** [comment]
@jlozadad I just started to work on it.

https://github.com/Octopussy-Project/ansible-role-octopussy

I will update my 'Installation part' with a lot of stuff discovered while working on this ansible role.
I will work on Debian, Fedora & Ubuntu installation before that.

**Comment by sebthebert** [comment]
I just merged my [updated documentation](https://github.com/Octopussy-Project/Octopussy_Documentation/pull/10).
